### ISSUE TITLE
Enable Global Prefix for Type Access

### ISSUE THREAD

**Issue by aaronmallen** [domainic/domainic#96]
**As a** Ruby developer  
**I want to** enable a global prefix for type access  
**So that** I can easily reference and autoload types dynamically with minimal overhead

---

#### Acceptance Criteria

1. Developers can enable a global prefix for types via configuration:
   ```ruby
   Domainic::Type.configure do |config|
     config.enable_global_prefix
   end
   ```

2. The default prefix should be `T`, but it can be configured:
   ```ruby
   Domainic::Type.configure do |config|
     config.prefix_global_with(:D)
   end
   ```

3. Types should be accessible through the prefix, for example:
   ```ruby
   T.Array.of(String)
   ```

4. The prefix module should inject itself into `Kernel`, autoloading types dynamically.

5. Only the referenced types should be loaded into memory, ensuring that unused types are not loaded.

6. Comprehensive specs to test that the global prefix is enabled, types are accessible, and autoloading functions correctly.

---

#### Tasks

- [ ] Implement the ability to enable a global prefix for types.
- [ ] Inject a prefix module onto `Kernel` for autoloading types dynamically.
- [ ] Ensure that types are only loaded as they are referenced.
- [ ] Write specs to cover enabling the global prefix and type access.
